version: "3.1"

networks:
    on_net:

services:
    app:
        build:
            dockerfile: Dockerfile
            context: ./
        image: dennis199441/open-notifier:latest
        restart: always
        env_file:
            - variables.env
        ports:
            - 9400:9400
        networks:
            - on_net
